### ISSUE TITLE
About checkpoint 

### ISSUE THREAD

**Issue by YuanLi95** [rishubhpar/PreciseControl#1]
Hi, Thanks for your code. When I ran the test, I found an error: FileNotFoundError: [Errno 2] No such file or directory: 'logs/id_name/checkpoints/lora_params-49.pt'. I guess it's because I don't have the checkpoint for fine-tuning. I hope you can provide it. 

Sincerely, 
LI Yuan

**Comment by sachidanandvs** [comment]
Hi, thank you for your interest, that is the path for the folder that will be created after you finetune for a particular identity, which is usually saved under logs folder. you can check the logs folder and see what 'id_name' is present and give that during testing as argument.

For sample, we have added a finetuned weights for tim cook identity here:[cook](https://drive.google.com/drive/folders/1ScrLSa-S1Epc8fO_FBkMJvFae9EO226b?usp=drive_link). You can download this under logs directory and run test file with id_name as cook
