### ISSUE TITLE
How to train the first stage of the mapper M

### ISSUE THREAD

**Issue by xiangliu886** [rishubhpar/PreciseControl#2]
How to train the first stage of the mapper M?Can you introduce how the data is preprocessed in the first stage?

**Comment by sachidanandvs** [comment]
You can give the path of ffhq dataset folder in `./configs/stable-diffusion/aigc_id.yaml` and run '01_start_train.sh' file to train the mapper. Other parameter like iteration, identity loss weight everything can be tuned in the yaml file. The dataloader(FFhq_dataset) is in `./ldm/data/face_id.py` you can check that if you need to change something. Let me know if its not working.
