### ISSUE TITLE
all_deltaw_disct.json

### ISSUE THREAD

**Issue by xiangliu886** [rishubhpar/PreciseControl#5]
May I ask how the file **all_deltaw_disct.json** was obtained？

**Comment by sachidanandvs** [comment]
Hi, thank you for your interest, we use edit directions from methods like FLAME and InterfaceGAN and use that to create paired dataset with edited and unedited image, and then we take mean of difference of the inverted e4e latents to get the edit directions. 

 You can directly use other GAN editing paper's latent direction too, but you have to find the proper edit strength needed to perform the edits. Here in the dataset we scaled the edit strength properly from different methods, so all edits will occur in range 0-2.5. 

You can check the norm of the edits in the json file if you wish to try other methods edit direction.

FLAME - https://sites.google.com/view/flamelatentediting/
InterFaceGAN - https://genforce.github.io/interfacegan/
