### ISSUE TITLE
model_ir_se50.pt

### ISSUE THREAD

**Issue by hou-f** [rishubhpar/PreciseControl#6]
Hello, dear author. Thanks for your code. However, I have a question that the **model_ir_se50.pt** file how can I get. Please tell me.

**Comment by sachidanandvs** [comment]
Hi, thank you for pointing it out, you can download the weights from [here](https://huggingface.co/sachi1/PreciseControl/tree/main) for now, we will update the weights in drive also

**Comment by hou-f** [comment]
![Snipaste_2024-10-18_16-03-23](https://github.com/user-attachments/assets/5e2278ec-c4a8-428e-a07e-05091c15bbac)
Sorry, I have met another question when set enviornment as the picture showed above. Please tell me again, thanks.

**Comment by sachidanandvs** [comment]
hi, It seems to be a conda issue, it working fine for me. Is this only happening while setting up this environment?

**Comment by hou-f** [comment]
yeah, our operational system may be differerent. My system is Windows. Ur system is linux? Thanks for your aaply!

**Comment by sachidanandvs** [comment]
yeah ours is linux system, where you able to fix it now
